// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrBk_Jx_q6n0LDqWtc19QzrePipUycMJg',
    appId: '1:851468904224:web:2ee5516173cdcbfe741945',
    messagingSenderId: '851468904224',
    projectId: 'shahan-app',
    authDomain: 'shahan-app.firebaseapp.com',
    storageBucket: 'shahan-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT2mOLNBWtxRozC-Fi1ayEWaIbyABfE5c',
    appId: '1:851468904224:android:dc8988b53ccc5655741945',
    messagingSenderId: '851468904224',
    projectId: 'shahan-app',
    storageBucket: 'shahan-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC0e37_rTx46V74CMmwKLCHhe2pEZfbyM',
    appId: '1:851468904224:ios:80061c14e6efc0e3741945',
    messagingSenderId: '851468904224',
    projectId: 'shahan-app',
    storageBucket: 'shahan-app.appspot.com',
    iosBundleId: 'com.example.shahan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC0e37_rTx46V74CMmwKLCHhe2pEZfbyM',
    appId: '1:851468904224:ios:80061c14e6efc0e3741945',
    messagingSenderId: '851468904224',
    projectId: 'shahan-app',
    storageBucket: 'shahan-app.appspot.com',
    iosBundleId: 'com.example.shahan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrBk_Jx_q6n0LDqWtc19QzrePipUycMJg',
    appId: '1:851468904224:web:4a38c4c9d544252d741945',
    messagingSenderId: '851468904224',
    projectId: 'shahan-app',
    authDomain: 'shahan-app.firebaseapp.com',
    storageBucket: 'shahan-app.appspot.com',
  );
}
